### ISSUE TITLE
Whether to support.NET 6

### ISSUE THREAD

**Issue by quan0zhou** [yhuse/SunnyUI#37]
Unloaded control found in.NET 6

**Comment by yhuse** [comment]
请看README，描述的很清楚



---Original---
From: ***@***.***&gt;
Date: Tue, Aug 24, 2021 11:10 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [yhuse/SunnyUI] Whether to support.NET 6 (#37)




 
Unloaded control found in.NET 6
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yhuse** [comment]
从core到net5，winform并没有做多大的变动，反而增加了不少Bug。还是.Net framework稳定。
