### ISSUE TITLE
多个屏幕下，主窗体无法最大化

### ISSUE THREAD

**Issue by howarwang** [yhuse/SunnyUI#39]
有两个屏幕，主屏幕是笔记本1080P分辨率，第二屏幕为2k分辨率的显示器。
在Extend 模式下：
程序在笔记本上运行后，可以满屏（1080P），但是拖拽到2K分辨率屏幕后，窗口大小依然保持1920x1080. 无法最大化到2560x1440.
 在 Second screen only模式下，也就是只有一个2K屏幕下，窗体可以最大化。

估计是不是窗体在不同屏幕切换没有考虑到分辨率的变化？
另外测试了原生的窗体，没有出现这个问题。

**Comment by yhuse** [comment]
Github下载最新的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月8日(周三) 上午7:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [yhuse/SunnyUI] 多个屏幕下，主窗体无法最大化 (#39)




 
有两个屏幕，主屏幕是笔记本1080P分辨率，第二屏幕为2k分辨率的显示器。
 在Extend 模式下：
 程序在笔记本上运行后，可以满屏（1080P），但是拖拽到2K分辨率屏幕后，窗口大小依然保持1920x1080. 无法最大化到2560x1440.
 在 Second screen only模式下，也就是只有一个2K屏幕下，窗体可以最大化。
 
估计是不是窗体在不同屏幕切换没有考虑到分辨率的变化？
 另外测试了原生的窗体，没有出现这个问题。
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by howarwang** [comment]
目前是从nuget 下载的SunnyUI.Net V3.0.6

**Comment by howarwang** [comment]
谢谢，下载了GitHub最新版本，问题解决。
另外顺便问：SunnyUi.common.dll是如何生成？ 源码编译似乎只是生成SunnyUI.dll

**Comment by howarwang** [comment]
problem solved
